-- 0010: versión 4.0.0 en BORRADOR (generado por scripts/gen-v4-seed.mjs desde supabase/seed/noticias-v4.json; no editar a mano)
-- 10 noticias (5 reales, 5 falsas) con titulares corregidos y tres fuentes consultables cada una.
-- Las tarjetas del banco se actualizan (sube su revisión) y la versión copia esa revisión, igual que al armarla desde el panel.
-- Las imágenes son las mismas de la 3.x (display del banco). No se activa: eso lo hace el owner desde el panel.

insert into public.studies (code, version, title, description, status, config, changelog)
values ('lo-reenviarias', '4.0.0', '¿Lo reenviarías? — responsabilidad antes de compartir',
  'Cada noticia: reenviar, reenviar con aviso, verificar primero o no reenviar; si verifica, abre una fuente, dice qué dice y decide; después declara si la cree (Sí, No, No sé). Imagen al azar en la mitad de las tarjetas. La encuesta de hábitos es un instrumento aparte y no se vincula con las partidas.',
  'draft', '{"mode":"responsabilidad","items_per_session":10,"seconds_per_item":20,"verify_seconds":60,"min_read_ms":2000,"start_points":600,"image_share":0.5,"why_items":2,"hints_per_session":0,"show_crowd_feedback":false,"leaderboard":true,"percentile_min_n":20,"public_stats_min_n":10,"max_sessions_per_minute":120}'::jsonb,
  'Metodológico: la variable principal pasa a ser la difusión simulada sin verificación previa (E1+E2 sobre R). La creencia se pregunta después de decidir y es lo único que da puntos. Titulares corregidos (r_cuba, r_arancel, f_sinpe y otros). Sin lupas ni alcance simulado. No comparable con 1.0.0–3.1.0.')
on conflict (code, version) do nothing;

insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, required, position, min_length, max_length)
select id, 'primera_vez', 'pre', 'single', '¿Es la primera vez que juegas este juego?', array['Sí, es la primera vez','No, ya había jugado']::text[], true, 1, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '4.0.0'
on conflict (study_id, question_key) do nothing;

-- r_arancel
update public.news_bank set
  headline = 'EE.UU. sube a 12,5% el arancel a parte de las exportaciones ticas por no prohibir importar bienes de trabajo forzoso', is_real = true, category = 'Economía y comercio',
  source_name = 'USTR (Oficina del Representante Comercial de EE.UU.)', source_url = 'https://ustr.gov/about/policy-offices/press-office/press-releases/2026/july/ustr-takes-action-forced-labor-section-301-investigations', source_published_on = '2026-07-23',
  explanation = 'Es real. Desde el 24/07/2026 EE.UU. cobra 12,5% (antes 10%) a parte de las exportaciones de Costa Rica; el motivo es que el país no tiene una prohibición efectiva para frenar importaciones hechas con trabajo forzoso, no que haya trabajo forzoso en Costa Rica.', hint = 'La Oficina de Comercio de EE.UU. (USTR) lo anunció el 23 de julio de 2026 y medios nacionales lo publicaron ese mismo día.', red_flags = array[]::text[],
  display = display || jsonb_build_object('src_label', 'Fuente citada: La República / Infobae'),
  validation_status = 'verificada', validation_notes = 'USTR tomó acción final el 23/07/2026 en 60 investigaciones de la Sección 301 por ''failure to impose and effectively enforce a prohibition on the importation of goods produced with forced labor''. Costa Rica aparece en la lista de 60 economías (fact sheet de marzo de 2026, n.º 14) y no está en el grupo del 10%, por lo que le corresponde el 12,5% (''all other investigated economies''). Infobae precisa que reemplaza la sobretasa temporal de 10% vigente desde febrero, que aplica solo a parte de las exportaciones (excluye café, piña, banano, dispositivos médicos, farmacéuticos, semiconductores, entre otros) y que rige desde las 12:01 a. m. (hora del Este) del 24/07/2026. COMEX alegó que no se aportó evidencia de que productos costarricenses se fabriquen con trabajo forzoso. La nota de AP citada en la tarjeta 3.1.0 no se localizó.',
  consult_sources = '[{"kind":"oficial","label":"USTR – comunicado de acción final (Sección 301, trabajo forzoso)","excerpt":"El 23/07/2026 la USTR tomó acción final contra 60 economías por no imponer ni aplicar de forma efectiva una prohibición a importar bienes hechos con trabajo forzoso: 10% para un grupo de países y 12,5% para las demás economías investigadas.","says":"confirma","simulated":false,"url":"https://ustr.gov/about/policy-offices/press-office/press-releases/2026/july/ustr-takes-action-forced-labor-section-301-investigations"},{"kind":"medio","label":"Infobae Costa Rica","excerpt":"EE.UU. eleva de 10% a 12,5% el arancel a parte de las exportaciones de Costa Rica desde el 24 de julio. La USTR concluyó que el país no tiene prohibición ni mecanismos efectivos para frenar la entrada de bienes hechos con trabajo forzoso. Café y piña, excluidos.","says":"confirma","simulated":false,"url":"https://www.infobae.com/costa-rica/2026/07/25/eeuu-eleva-a-125-el-arancel-para-parte-de-las-exportaciones-de-costa-rica-por-cuestionamientos-sobre-trabajo-forzado/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"Mario_CR","text":"¿O sea que en Costa Rica hay trabajo forzoso? No me lo creo."},{"who":"ana.exporta","text":"En la empresa nos dijeron que nuestro producto no paga el 12,5%, depende de cuál sea."},{"who":"pura_vida_88","text":"Otra vez Trump inventando aranceles, seguro es fake."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'r_arancel'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'r_arancel');

-- f_marihuana
update public.news_bank set
  headline = 'Desde noviembre será legal comprar marihuana recreativa en farmacias de Costa Rica', is_real = false, category = 'Política nacional',
  source_name = null, source_url = null, source_published_on = null,
  explanation = 'Es inventada para este juego. La ley vigente (Ley 10113) solo regula el cannabis para uso medicinal y el cáñamo; el proyecto de marihuana recreativa de 2022 fue declarado inconstitucional por la Sala IV en noviembre de 2024.', hint = 'Hubo un proyecto del Gobierno para legalizarla, pero la Sala IV lo consideró inconstitucional y ninguna ley permite venderla en farmacias.', red_flags = array['No dice quién lo anunció ni cita ninguna ley.','Se apoya en un debate real (el proyecto de 2022) para parecer creíble.','Da una fecha cercana para que reacciones rápido.']::text[],
  display = display || jsonb_build_object('src_label', 'Sin fuente'),
  validation_status = 'ficticia_documentada', validation_notes = 'El Gobierno de Rodrigo Chaves anunció en octubre de 2022 un proyecto para legalizar la marihuana recreativa (La Nación, 05/10/2022). Teletica (27/11/2024) informa que el expediente 23.383 recibió dictamen negativo de mayoría en la Comisión de Ambiente y que la Sala Constitucional lo declaró inconstitucional (consulta del TSE sobre referéndum) por chocar con convenciones de la ONU sobre drogas. La norma vigente (Ley 10113 y su reglamento, Decreto 44585-MP-MAG-MS de 12/07/2024) regula el cannabis ''exclusivamente para uso medicinal y terapéutico'' y solo permite despachar preparaciones magistrales de cáñamo con receta. No se encontró ningún anuncio de venta recreativa en farmacias desde noviembre (búsqueda 10/10/2026). El enlace de El Observador citado en 3.1.0 no se pudo abrir (robots.txt bloquea la lectura automatizada).',
  consult_sources = '[{"kind":"oficial","label":"MAG – Reglamento a la Ley 10113 (Decreto 44585-MP-MAG-MS)","excerpt":"El reglamento de 2024 indica que la Ley 10113 regula el acceso al cannabis exclusivamente para uso medicinal y terapéutico, y que las farmacias solo despachan preparaciones de cáñamo con receta médica. No menciona uso recreativo.","says":"desmiente","simulated":false,"url":"https://www.mag.go.cr/legislacion/2024/de-44585.pdf"},{"kind":"medio","label":"Teletica","excerpt":"En noviembre de 2024 la Sala IV resolvió que el proyecto del Gobierno para regular la marihuana recreativa (expediente 23.383) es inconstitucional por chocar con tres convenciones de la ONU sobre drogas. La Comisión de Ambiente ya lo había dictaminado negativamente.","says":"desmiente","simulated":false,"url":"https://www.teletica.com/politica/proyecto-para-regular-marihuana-recreativa-es-inconstitucional-resuelve-sala-iv_372960"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"dani_420","text":"¡Por fin! Ya era hora, en Uruguay es así desde hace años."},{"who":"Lu_Herrera","text":"¿Y en qué Gaceta salió? No veo nada en las noticias."},{"who":"profe_jorge","text":"Eso lo tumbó la Sala IV hace rato, ¿no?"}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'f_marihuana'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'f_marihuana');

-- r_cuba
update public.news_bank set
  headline = 'Canciller confirma que Costa Rica rompió relaciones con Cuba; el cierre de la embajada en La Habana se anunció en marzo', is_real = true, category = 'Política internacional',
  source_name = 'CR Hoy', source_url = 'https://crhoy.com/canciller-reafirma-rompimiento-de-relaciones-con-cuba/', source_published_on = '2026-09-20',
  explanation = 'Es real. En marzo de 2026 Costa Rica cerró su embajada y pidió salir al personal diplomático cubano, sin declarar entonces una ruptura; el 19/09/2026 el canciller confirmó públicamente el rompimiento de relaciones. Cuba dice que nunca fue notificada formalmente.', hint = 'El canciller Manuel Tovar lo dijo el 18 y 19 de septiembre de 2026; el cierre de la embajada se anunció el 18 de marzo.', red_flags = array[]::text[],
  display = display || jsonb_build_object('src_label', 'Fuente citada: CR Hoy / Tico Times'),
  validation_status = 'verificada', validation_notes = '18/03/2026: el Gobierno de Rodrigo Chaves anunció el cierre de la embajada en La Habana y pidió a Cuba retirar a su personal diplomático en San José, dejando solo funcionarios consulares (CR Hoy 18/03/2026; ADN40 18/03/2026). CR Hoy de esa fecha no usa la palabra ''ruptura'' y habla de poder ''retomar plenamente las relaciones''. Según la Cancillería cubana (citada por Tico Times y CR Hoy), la nota del 17/03 decía que las medidas no constituían una ruptura. 18/09/2026: la Cancillería dijo a EFE que las relaciones ''están rotas'' desde marzo y el canciller Manuel Tovar lo afirmó al Miami Herald (Diario El Mundo/EFE, 18/09/2026). 19/09/2026: Tovar escribió en X ''Somos firmes y claros en nuestro rompimiento de relaciones diplomáticas con el régimen castrista'' (CR Hoy 20/09/2026; TVN 19/09/2026; Tico Times 20/09/2026). Cuba dice que se enteró por la prensa. No se pudo abrir ningún comunicado oficial: rree.go.cr no muestra comunicado sobre Cuba en su portada y cubaminrex.cu bloquea la lectura automatizada. Matiz: hay versiones distintas sobre la fecha de la ruptura (el Gobierno la sitúa en marzo); el titular solo afirma lo que es verificable: la confirmación del canciller y el anuncio del cierre en marzo.',
  consult_sources = '[{"kind":"oficial","label":"Ministerio de Relaciones Exteriores y Culto (rree.go.cr)","excerpt":"La portada de la Cancillería no muestra un comunicado sobre Cuba. La ruptura se conoció por declaraciones del canciller Manuel Tovar en X y a la prensa (18-19/09/2026), no por un comunicado publicado en este sitio.","says":"nada_claro","simulated":false,"url":"https://www.rree.go.cr/"},{"kind":"medio","label":"CR Hoy","excerpt":"El 19/09/2026 el canciller Manuel Tovar confirmó en X el rompimiento de relaciones con Cuba. Cuba afirma que solo recibió una nota el 17 de marzo sobre el cierre de la embajada y que el Gobierno anterior dijo que no era una ruptura total.","says":"confirma","simulated":false,"url":"https://crhoy.com/canciller-reafirma-rompimiento-de-relaciones-con-cuba/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"Rebeca_SJ","text":"Eso fue en marzo, ¿no? Ya habían cerrado la embajada."},{"who":"elcubanoentico","text":"Mi familia allá dice que nadie les avisó nada oficial."},{"who":"Andres.M","text":"Seguro es otra noticia vieja que reciclan."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'r_cuba'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'r_cuba');

-- f_ingles
update public.news_bank set
  headline = 'Por el recorte de presupuesto, el MEP eliminará las clases de inglés en primaria a partir de 2027', is_real = false, category = 'Educación',
  source_name = null, source_url = null, source_published_on = null,
  explanation = 'Es inventada para este juego, pero se monta sobre una noticia real: el proyecto de presupuesto 2027 reduce unos ₡19 mil millones al MEP. El MEP sigue con inglés en primaria (por ejemplo, su Festival de Inglés 2026 incluye I y II ciclos).', hint = 'El recorte al presupuesto del MEP sí es real, pero no hay ningún anuncio sobre eliminar el inglés en primaria.', red_flags = array['Mezcla un hecho real con uno falso: es la técnica más efectiva.','No cita comunicado del MEP.','Busca indignación.']::text[],
  display = display || jsonb_build_object('src_label', 'Sin fuente'),
  validation_status = 'ficticia_documentada', validation_notes = 'Búsqueda 10/10/2026: no se encontró anuncio del MEP sobre eliminar inglés en primaria. La página de noticias del MEP (1-9/10/2026) no tiene nada al respecto. El manual oficial del Festival de Inglés 2026 (MEP, Dirección de Desarrollo Curricular) incluye orientaciones para I y II ciclos. Sobre 2027, el MEP prepara reducir el calendario escolar y el ministro Leonardo Sánchez aseguró que no se reducirían contenidos (CR Hoy, 28/08/2026). El recorte presupuestario es real (ver r_recorte). No hay una página que desmienta textualmente la afirmación; por eso las fuentes del juego se marcan ''nada_claro''.',
  consult_sources = '[{"kind":"oficial","label":"MEP – Manual del Festival de Inglés 2026","excerpt":"Documento del MEP para 2026 con orientaciones del Festival de Inglés, con una sección para Primero y Segundo Ciclos (primaria). No habla de 2027 ni de eliminar la materia.","says":"nada_claro","simulated":false,"url":"https://drea.mep.go.cr/sites/default/files/publicaciones-anexos-2026/MANUAL%20DE%20FESTIVAL%20DE%20INGL%C3%89S%202026.pdf"},{"kind":"medio","label":"CR Hoy","excerpt":"El MEP prepara un calendario escolar más corto para 2027; el ministro Leonardo Sánchez asegura que los cambios no reducirían los contenidos. La nota no menciona eliminar el inglés.","says":"nada_claro","simulated":false,"url":"https://crhoy.com/nacionales/mep-prepara-reduccion-del-calendario-escolar-para-2027/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"mamá_de_2","text":"¡Qué barbaridad! Mis hijos apenas están aprendiendo."},{"who":"teacher_karla","text":"Soy docente de inglés en una escuela y no nos han dicho nada de eso."},{"who":"JP_Alajuela","text":"Con el recorte todo es posible..."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'f_ingles'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'f_ingles');

-- r_hermano
update public.news_bank set
  headline = 'Hermano del ministro de Justicia duplicó su salario: pasó de ₡2,1 a ₡4,2 millones con una plaza de confianza en el ICE', is_real = true, category = 'Función pública',
  source_name = 'CR Hoy', source_url = 'https://crhoy.com/nacionales/hermano-de-ministro-tuvo-mejora-salarial-de-₡2-millones-gracias-a-puesto-en-el-gobierno/', source_published_on = '2026-10-03',
  explanation = 'Es real. Según CR Hoy, Esteban Aguilar, hermano del ministro Gabriel Aguilar, pasó de ganar ₡2,1 millones como fiscal a ₡4,2 millones como asesor de la Gerencia General del ICE desde junio de 2026. Es un reportaje periodístico; el ICE confirmó el nombramiento y el salario.', hint = 'CR Hoy lo publicó el 3 de octubre de 2026; el ICE confirmó el nombramiento en junio.', red_flags = array[]::text[],
  display = display || jsonb_build_object('src_label', 'Fuente citada: CR Hoy'),
  validation_status = 'verificada', validation_notes = 'CR Hoy (03/10/2026): Esteban Aguilar Vargas, exfiscal de cibercrimen (₡2,1 millones), pasó por una subdirección en el Micitt (₡3,2 millones base) y desde junio de 2026 es asesor de la Gerencia General del ICE con ₡4.206.545 mensuales; el ICE dijo que fue un nombramiento ocasional sin concurso ni informe técnico de RR. HH. CR Hoy (18/06/2026) y Delfino (19/06/2026) reportan que el ICE confirmó la contratación y el salario. No hay resolución oficial publicada; el portal de transparencia del ICE ofrece índice salarial y planilla, pero no nombramientos individuales.',
  consult_sources = '[{"kind":"oficial","label":"ICE – Portal de Transparencia","excerpt":"El ICE indica que publica su índice salarial y su planilla institucional (nombre, clase de puesto y salario bruto). La página no detalla nombramientos individuales ni menciona este caso.","says":"nada_claro","simulated":false,"url":"https://www.grupoice.com/wps/portal/ICE/Transparencia"},{"kind":"medio","label":"CR Hoy","excerpt":"Esteban Aguilar, hermano del ministro de Justicia, pasó de ₡2,1 millones como fiscal a ₡4.206.545 como asesor de la Gerencia General del ICE desde junio de 2026. El ICE dijo que fue un nombramiento ocasional sin concurso.","says":"confirma","simulated":false,"url":"https://crhoy.com/nacionales/hermano-de-ministro-tuvo-mejora-salarial-de-₡2-millones-gracias-a-puesto-en-el-gobierno/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"Rigo_Heredia","text":"Siempre lo mismo, los puestos para la familia."},{"who":"laura.v","text":"¿Eso es legal? Si no hubo concurso habría que investigar."},{"who":"tico_neutral","text":"CR Hoy siempre exagera, hay que ver la otra versión."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'r_hermano'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'r_hermano');

-- f_ejercito
update public.news_bank set
  headline = 'URGENTE: la Asamblea Legislativa aprobó en primer debate volver a crear el ejército', is_real = false, category = 'Política nacional',
  source_name = null, source_url = null, source_published_on = null,
  explanation = 'Es inventada para este juego. El artículo 12 de la Constitución proscribe el ejército como institución permanente, y reformar la Constitución sigue un trámite especial (art. 195) que no se puede delegar a comisiones.', hint = 'La abolición del ejército está en el artículo 12 de la Constitución; cambiarlo exigiría una reforma constitucional con cobertura en todos los medios.', red_flags = array['Mayúsculas y "URGENTE" para generar alarma.','Sería una reforma constitucional: imposible que pase en silencio.','No hay votación registrada ni medio que lo publique.']::text[],
  display = display || jsonb_build_object('src_label', 'Sin fuente'),
  validation_status = 'ficticia_documentada', validation_notes = 'Constitución Política, art. 12: ''Se proscribe el Ejército como institución permanente.'' Art. 123: los proyectos de reforma constitucional siguen el trámite del art. 195; art. 124: no se pueden delegar a comisiones. No se pudo abrir el texto del art. 195 completo en las copias consultadas (truncadas), por lo que no se citan sus requisitos exactos. Contexto 2026: en marzo, el presidente Chaves dijo que cualquier apoyo de fuerza militar extranjera tendría que pasar por la Asamblea (EFE vía Estrategia & Negocios, 12/03/2026); no se reporta ningún proyecto para recrear el ejército. No se encontró ninguna votación así (búsqueda 10/10/2026).',
  consult_sources = '[{"kind":"oficial","label":"Constitución Política de Costa Rica (Poder Judicial)","excerpt":"Artículo 12: se proscribe el Ejército como institución permanente; para el orden público habrá fuerzas de policía, y solo por convenio continental o para la defensa nacional podrán organizarse fuerzas militares, siempre subordinadas al poder civil.","says":"desmiente","simulated":false,"url":"https://pj.poder-judicial.go.cr/images/documentos/normativa/Constitucion_Politica_Costa_Rica.pdf"},{"kind":"medio","label":"Estrategia & Negocios / EFE","excerpt":"En marzo de 2026 el presidente Chaves dijo que pedir apoyo militar extranjero tendría que pasar por la Asamblea. La nota recuerda que el ejército se abolió en 1948 (art. 12) y no menciona ningún proyecto para recrearlo.","says":"nada_claro","simulated":false,"url":"https://www.revistaeyn.com/centroamericaymundo/costa-rica-defiende-escudo-de-las-americas-y-no-descarta-apoyo-militar-de-eeuu-a-su-pais-GE29696167"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"Fer_Cartago","text":"¡No puede ser! ¿Y la Constitución?"},{"who":"seguridad_ya","text":"Con tanta violencia, ojalá sea cierto."},{"who":"historia_cr","text":"Eso necesitaría reforma constitucional, no se aprueba así de un día para otro."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'f_ejercito'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'f_ejercito');

-- r_bus
update public.news_bank set
  headline = 'El pasaje de la ruta 220 en Alajuela pasó de ₡260 a ₡1.000 tras la aprobación de la ARESEP', is_real = true, category = 'Transporte y costo de vida',
  source_name = 'La Teja', source_url = 'https://www.lateja.cr/finanzas-y-tecnologia/bus-de-ruta-de-alajuela-amanecio-este-miercoles/PYIMWBYERVCPJMHNVS4ZA3DRWA/story/', source_published_on = '2026-10-07',
  explanation = 'Es real. La ARESEP aprobó la tarifa de la ruta 220 (Alajuela–barrio San José) a inicios de octubre y La Teja informó el 7 de octubre de 2026 que ya se cobraban ₡1.000.', hint = 'Lo publicaron La Teja y CR Hoy el 7 de octubre de 2026.', red_flags = array[]::text[],
  display = display || jsonb_build_object('src_label', 'Fuente citada: La Teja'),
  validation_status = 'verificada', validation_notes = 'La Teja (07/10/2026, 10:20 a. m.): ruta 220 ''Alajuela, barrio San José y viceversa'', operada por Transportes Filemón Villalobos e Hijos S.A., pasó de ₡260 a ₡1.000 (+₡740); la ARESEP lo aprobó ''la semana pasada'' y su vocero Paolo Varela explicó que se resolvió con un esquema operativo de 1994 que el CTP no actualizó. CR Hoy (22/07/2026) informó la solicitud (expediente ET-064-2026) y la audiencia pública del 01/09/2026; CR Hoy (07/10/2026) recoge las quejas de vecinos. La página oficial de la audiencia ET-064-2026 confirma la solicitud y la audiencia, pero no muestra la resolución final ni la tarifa aprobada; no se localizó la resolución RE- de ARESEP.',
  consult_sources = '[{"kind":"oficial","label":"ARESEP – Audiencia pública ET-064-2026","excerpt":"Convocatoria a audiencia virtual el 1/09/2026 por la solicitud de fijación tarifaria ordinaria de la ruta 220 Alajuela–Barrio San José (Transportes Filemón Villalobos e Hijos). La página no muestra la tarifa pedida ni la resolución final.","says":"nada_claro","simulated":false,"url":"https://aresep.go.cr/audiencias/et-064-2026"},{"kind":"medio","label":"La Teja","excerpt":"El 7/10/2026 La Teja informó que el pasaje de la ruta 220 Alajuela–barrio San José pasó de ₡260 a ₡1.000. La ARESEP lo aprobó la semana anterior y explicó que resolvió con un esquema operativo de 1994.","says":"confirma","simulated":false,"url":"https://www.lateja.cr/finanzas-y-tecnologia/bus-de-ruta-de-alajuela-amanecio-este-miercoles/PYIMWBYERVCPJMHNVS4ZA3DRWA/story/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"vecina_lucia","text":"¡₡52 mil al mes solo para ir a trabajar! Esto es un abuso."},{"who":"busero_cr","text":"La tarifa vieja no cubría ni el diésel."},{"who":"Kevin_A","text":"Eso es fake, ninguna ruta puede subir tanto de un solo golpe."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'r_bus'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'r_bus');

-- f_ccss
update public.news_bank set
  headline = 'La CCSS dejará de atender emergencias a personas que no tengan el seguro al día desde enero. ¡Pásalo!', is_real = false, category = 'Salud',
  source_name = null, source_url = null, source_published_on = null,
  explanation = 'Es inventada para este juego. Los artículos 61 y 74 del Reglamento del Seguro de Salud de la CCSS establecen que las urgencias se atienden de inmediato, aun a personas no aseguradas; el cobro, si corresponde, se hace después.', hint = 'No hay comunicado de la CCSS y su propio Reglamento del Seguro de Salud obliga a atender de inmediato las urgencias, con o sin seguro.', red_flags = array['Pide "pásalo": las instituciones no comunican así.','Genera miedo sobre un tema de salud.','No hay comunicado oficial.']::text[],
  display = display || jsonb_build_object('src_label', 'Sin fuente'),
  validation_status = 'ficticia_documentada', validation_notes = 'Art. 61: ''En caso de no asegurados, cuando la atención sea urgente, serán atendidos de inmediato, bajo su responsabilidad económica, entendiéndose que el pago podrá hacerse, en esta hipótesis, después de recibir la atención médica.'' Art. 74: ''Cuando la necesidad de atención médica sea urgente, ésta se brindará de forma inmediata''; quien no acredite su condición ''será atendido si se trata de urgencia o de emergencia''. Texto leído en el portal eRegulations de Costa Rica (copia del reglamento); la copia en asamblea.go.cr no se pudo abrir (robots.txt). La Sala Constitucional (sentencia 10060-2016, según El Mundo CR 31/08/2016) y la CCSS (CR Hoy 10/11/2020: ''A las personas no aseguradas se les atiende en caso de emergencia o urgencia, luego se les hace el proceso de cobro'') confirman el criterio. No se encontró comunicado de la CCSS sobre un cambio para enero (búsqueda 10/10/2026). No se verificó si existe una versión más reciente del reglamento con otra redacción.',
  consult_sources = '[{"kind":"oficial","label":"CCSS – Reglamento del Seguro de Salud, arts. 61 y 74","excerpt":"Art. 61: los no asegurados con atención urgente serán atendidos de inmediato y pueden pagar después. Art. 74: cuando la atención sea urgente se brindará de forma inmediata; quien llegue sin documentos será atendido si es urgencia o emergencia.","says":"desmiente","simulated":false,"url":"https://costarica.eregulations.org/media/reglamento%20del%20seguro%20de%20salud.pdf"},{"kind":"medio","label":"CR Hoy","excerpt":"La CCSS explicó que a las personas no aseguradas se les atiende en caso de emergencia o urgencia y luego se hace el proceso de cobro; para consultas no urgentes primero se revisa el derecho.","says":"desmiente","simulated":false,"url":"https://crhoy.com/nacionales/ciudadano-uso-servicios-de-la-ccss-sin-tener-seguro-y-ahora-le-debe-300-millones-de-colones/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"doña_marta","text":"¡Dios guarde! ¿Y si a uno le da un infarto?"},{"who":"enfermero_ebais","text":"En emergencias se atiende a todo el mundo; después se cobra si no tiene seguro."},{"who":"carlos_r","text":"Con la crisis de la Caja ya no me extraña nada."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'f_ccss'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'f_ccss');

-- r_recorte
update public.news_bank set
  headline = 'Gremios rechazan recorte de ₡19 mil millones al MEP en el presupuesto 2027: alertan por becas y alimentación estudiantil', is_real = true, category = 'Educación',
  source_name = 'CR Hoy', source_url = 'https://crhoy.com/nacionales/sindicatos-cuestionan-recorte-de-₡19-mil-millones-al-presupuesto-del-mep/', source_published_on = '2026-09-03',
  explanation = 'Es real. El proyecto de presupuesto 2027 asigna al MEP unos ₡19.230 millones menos que en 2026, y gremios como APSE, ANDE, SEC y Colypro advirtieron que podría afectar becas, alimentación estudiantil y a los estudiantes más vulnerables.', hint = 'Lo publicaron CR Hoy y Delfino el 3 de septiembre de 2026, con cifras del proyecto de presupuesto 2027 de Hacienda.', red_flags = array[]::text[],
  display = display || jsonb_build_object('src_label', 'Fuente citada: CR Hoy / Delfino'),
  validation_status = 'verificada', validation_notes = 'Folleto Presupuesto Nacional 2027 (Ministerio de Hacienda, DGPN): MEP ₡2.771.516,7 millones (2026) → ₡2.752.287,0 millones (proyecto 2027), -0,7% (≈ ₡19.229,7 millones). El folleto se leyó en una copia alojada en actualidadtributaria.com; no se pudo abrir en hacienda.go.cr. CR Hoy (03/09/2026): APSE, ANDE y Colypro cuestionan el recorte de ~₡19.230 millones; Colypro pide no reducir la ''alimentación estudiantil''. Delfino (03/09/2026): el SEC rechaza la reducción y menciona becas entre las áreas en riesgo. Diario Extra (video) también lo reporta con SIDE, SEC y APSE y menciona becas y comedores, pero su página muestra fechas contradictorias (04/09 vs 08/10/2026); se conserva solo como contexto. Contexto: el ministro Leonardo Sánchez atribuye la baja a la caída de matrícula (Diario Extra, fechas también inconsistentes: 23/09 vs 09/10/2026).',
  consult_sources = '[{"kind":"oficial","label":"Ministerio de Hacienda – Folleto Presupuesto Nacional 2027","excerpt":"El folleto de Hacienda sobre el proyecto de presupuesto 2027 asigna al MEP ₡2.752.287 millones, frente a ₡2.771.516,7 millones en 2026: una baja de 0,7% (unos ₡19.230 millones).","says":"confirma","simulated":false,"url":"https://actualidadtributaria.com/Uploads/Documentos/Folleto_Presupuesto_Nacional_2027.pdf"},{"kind":"medio","label":"CR Hoy","excerpt":"APSE, ANDE y Colypro cuestionan el recorte de unos ₡19.230 millones al MEP para 2027. APSE advierte que golpearía a los estudiantes más vulnerables y Colypro pide no reducir servicios como la alimentación estudiantil.","says":"confirma","simulated":false,"url":"https://crhoy.com/nacionales/sindicatos-cuestionan-recorte-de-₡19-mil-millones-al-presupuesto-del-mep/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"profe_andrea","text":"Otra vez recortando en educación, ¿y los comedores?"},{"who":"datos_cr","text":"Dicen que es porque hay menos estudiantes cada año."},{"who":"mae_sarchí","text":"Esto lo inventan los sindicatos para hacer huelga."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'r_recorte'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'r_recorte');

-- f_sinpe
update public.news_bank set
  headline = 'A partir del 1 de noviembre SINPE Móvil cobrará ₡150 por cada transferencia. ¡Avísale a todos!', is_real = false, category = 'Finanzas personales',
  source_name = null, source_url = null, source_published_on = null,
  explanation = 'Es inventada para este juego. No existe un cobro de ₡150 por cada SINPE Móvil: cada banco fija sus condiciones y varios cobran entre $2 y $3 (o ₡2.500 en BCT) solo cuando se supera un monto diario gratuito; el BCCR limitó a ₡100.000 diarios los envíos por SMS.', hint = 'No hay un cobro fijo por transferencia del BCCR; algunos bancos cobran comisión solo por encima de ciertos montos diarios.', red_flags = array['Pide reenviarlo a todos.','Fecha cercana para que reacciones sin pensar.','Ningún enlace ni comunicado oficial.']::text[],
  display = display || jsonb_build_object('src_label', 'Sin fuente'),
  validation_status = 'ficticia_documentada', validation_notes = 'Página de tarifas del SINPE (BCCR): las tarifas del SINPE las define el BCCR en el Reglamento del Sistema de Pagos; la comisión al cliente se fija según negociación con su entidad y la entidad puede cobrar menos o igual a las tarifas publicadas (la página no detalla montos de SINPE Móvil; no se pudo abrir la página específica de SINPE Móvil). El Financiero (31/08/2025): el BCCR acordó un tope de ₡100.000 diarios para transferencias por SMS; apps y banca en línea siguen con límites de cada banco. CR Hoy (16/10/2025): BCR gratis hasta ₡200.000 diarios y $3 por transacción por encima; Banco Popular gratis hasta ₡100.000 y $2 por encima; BCT ₡2.500 por transferencia adicional sobre ₡200.000; BN hasta ₡500.000 diarios por canales autenticados; BAC sin cambios en ese momento. El BCCR también aclaró (El Observador, 26/08/2025) que la nueva factura electrónica 4.4 no es un impuesto a SINPE Móvil. No se encontró ningún anuncio de un cobro de ₡150 por transferencia desde noviembre de 2026 (búsqueda 10/10/2026).',
  consult_sources = '[{"kind":"oficial","label":"BCCR – Tarifas y comisiones del SINPE","excerpt":"El BCCR define las tarifas del SINPE en el Reglamento del Sistema de Pagos. La comisión que paga el cliente se fija según lo que negocie con su banco, que puede cobrar menos o igual a las tarifas publicadas. No menciona un cobro fijo de ₡150.","says":"nada_claro","simulated":false,"url":"https://www.bccr.fi.cr/sistema-de-pagos/Tarifas-y-comisiones-del-SINPE"},{"kind":"medio","label":"CR Hoy","excerpt":"Cada banco aplica condiciones distintas: el BCR no cobra hasta ₡200.000 diarios y luego $3 por transacción; el Popular, gratis hasta ₡100.000 y luego $2. El BCCR fijó un tope de ₡100.000 diarios para envíos por SMS.","says":"desmiente","simulated":false,"url":"https://www.crhoy.com/varios-bancos-ya-estan-aplicando-cambios-en-sinpe-movil-enterese-aqui-cuales-son/"},{"kind":"comentarios","label":"Comentarios en redes","excerpt":"Lo que comentan otras personas en un grupo. Nadie cita una fuente.","says":"nada_claro","simulated":true,"comments":[{"who":"tia_marielos","text":"¡Ya me llegó también! Hay que avisarle a todo el mundo."},{"who":"fintech_tico","text":"Mi banco cobra solo si paso de cierto monto al día, no por cada SINPE."},{"who":"ronny.b","text":"Seguro es Hacienda queriendo meterle impuesto a todo."}]}]'::jsonb,
  revision = revision + 1, updated_at = now()
where item_key = 'f_sinpe'
  and not exists (select 1 from public.news_items n join public.studies s on s.id = n.study_id where s.version = '4.0.0' and n.item_key = 'f_sinpe');

insert into public.news_items (study_id, bank_id, item_key, item_version, headline, body_text, is_real, category, source_name, source_url,
                               source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes, consult_sources)
select st.id, b.id, b.item_key, b.revision, b.headline, b.body_text, b.is_real, b.category, b.source_name, b.source_url,
       b.source_published_on, b.explanation, b.hint, b.red_flags, b.display, b.validation_status, b.validation_notes, b.consult_sources
  from public.news_bank b cross join public.studies st
 where st.code = 'lo-reenviarias' and st.version = '4.0.0'
   and b.item_key in ('r_arancel', 'f_marihuana', 'r_cuba', 'f_ingles', 'r_hermano', 'f_ejercito', 'r_bus', 'f_ccss', 'r_recorte', 'f_sinpe')
on conflict (study_id, item_key) do nothing;
