-- 0002: catálogo del instrumento (generado por scripts/gen-seed-sql.mjs; no editar a mano)
-- Inserta versiones 1.0.0 (original, cerrada) y 2.0.0 (activa). ON CONFLICT DO NOTHING: no sobrescribe cambios posteriores.

insert into public.studies (code, version, title, description, status, config, changelog)
values ('lo-reenviarias', '1.0.0', '¿Lo reenviarías? — instrumento original (HTML monolítico)', 'Versión original entregada como HTML único. Se conserva para datos históricos migrados desde radiografia_respuestas.', 'closed', '{"items_per_session":10,"seconds_per_item":20,"hints_per_session":2,"show_crowd_feedback":true,"min_crowd_n":3,"timer_runs_with_reduced_motion":false}'::jsonb, 'Versión de referencia. Incluye retroalimentación de la multitud durante el juego y temporizador que no corría con ''reducir movimiento''.')
on conflict (code, version) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'opinion', 'pre', 'open', 'Si te llega una noticia impactante que no puedes verificar, ¿la compartes? ¿Por qué?', array[]::text[], 1, 3, 1500
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'verifica', 'pre', 'single', '¿Verificas una noticia antes de compartirla?', array['Siempre','A veces','Casi nunca']::text[], 2, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'compartio_falso', 'pre', 'single', '¿Has compartido algo que luego supiste que era falso?', array['Sí','No','No estoy seguro/a']::text[], 3, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'responsable', 'pre', 'single', 'Cuando una noticia falsa se vuelve viral, ¿quién tiene más responsabilidad?', array['Quien la crea','Quien la comparte','La red social','Todos por igual']::text[], 4, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'post_cambio', 'post', 'single', '¿Cambiarías tu forma de compartir noticias?', array['Sí, verificaría más','Tal vez','No, seguiré igual']::text[], 5, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_arancel', 'EE.UU. impone un arancel de 12,5% a Costa Rica por presunto trabajo forzoso en la cadena de suministro', true, 'Economía y comercio', 'La República (CR)', 'https://www.larepublica.net/noticia/ee-uu-cobrara-125-de-aranceles-a-exportaciones-ticas', '2026-07-23'::date, 'Es real. Ocurrió el 24 de julio de 2026.', 'La reportaron agencias internacionales y medios nacionales en julio de 2026.', array[]::text[], '{"who":"Tío Fernando","many":true,"band":"URGENTE","bg":"linear-gradient(135deg,#1F3B73,#B22234)","emo":"📦","emo2":"⛓️","src_label":"Fuente citada: AP / medios internacionales"}'::jsonb, 'requiere_precision', 'El arancel (de 10% a 12,5%, vigente 24/07/2026) se vincula a investigaciones de USTR sobre la falta de aplicación de una prohibición de importar bienes hechos con trabajo forzoso (60 economías), no a trabajo forzoso comprobado en la cadena costarricense; Infobae indica que aplica a ''parte de las exportaciones''. El titular simplifica. La fuente citada en la tarjeta (AP) no se localizó; se documenta La República, Infobae (25/07/2026) y Delfino. Fuentes adicionales: https://www.infobae.com/costa-rica/2026/07/25/eeuu-eleva-a-125-el-arancel-para-parte-de-las-exportaciones-de-costa-rica-por-cuestionamientos-sobre-trabajo-forzado/'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_marihuana', 'Desde noviembre será legal comprar marihuana recreativa en farmacias de Costa Rica', false, 'Política nacional', null, null, null, 'Es inventada para este juego.', 'Ningún medio la reporta y un cambio de ley así pasaría por la Asamblea con mucha cobertura.', array['No dice quién lo anunció ni cita ninguna ley.','Un cambio de ley así sería noticia en todos los medios.','Toca un tema polémico para que reacciones rápido.']::text[], '{"who":"Grupo U 🎓","many":false,"band":"NACIONAL","bg":"linear-gradient(135deg,#2F7D32,#A5D6A7)","emo":"🌿","emo2":"💊","src_label":"Sin fuente"}'::jsonb, 'requiere_correccion', 'La afirmación específica (venta legal en farmacias desde noviembre) es falsa. Pero existe un proyecto de ley del Gobierno sobre marihuana recreativa con cobertura mediática (p. ej. https://observador.cr/gobierno-enviara-proyecto-de-ley-para-legalizar-la-marihuana-recreativa-en-costa-rica/), por lo que la pista ''Ningún medio la reporta'' es imprecisa: sugerir ''Hay un proyecto en discusión, pero no es ley ni autoriza venta en farmacias''.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_cuba', 'Costa Rica rompe relaciones diplomáticas con Cuba y ordena cerrar su embajada', true, 'Política internacional', 'ADN40 / Reuters (18/03/2026)', 'https://www.adn40.mx/internacional/2026-03-18/costa-rica-cierra-su-embajada-en-cuba-la-habana-apunta-a-presiones-trump', '2026-03-18'::date, 'Es real. Sucedió el 18 de marzo de 2026.', 'Se publicó en medios nacionales e internacionales en marzo de 2026.', array[]::text[], '{"who":"Mamá","many":false,"band":"INTERNACIONAL","bg":"linear-gradient(135deg,#0B3D91,#CF142B)","emo":"🏛️","emo2":"✂️","src_label":"Fuente citada: CBS News"}'::jsonb, 'requiere_precision', 'El 17-18/03/2026 Costa Rica cerró su embajada y pidió la salida del personal diplomático cubano. Según Cuba (Tico Times, 20/09/2026), la nota de marzo no declaró una ruptura formal; el canciller confirmó la ruptura el 19/09/2026. ''Rompe relaciones'' en marzo es discutible. No se localizó la nota de CBS News citada. Ver https://ticotimes.net/2026/09/20/costa-rica-cuba-diplomatic-relations-break'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ingles', 'Por el recorte de presupuesto, el MEP eliminará las clases de inglés en primaria a partir de 2027', false, 'Educación', null, null, null, 'Es inventada para este juego, pero se monta sobre una noticia real: el recorte al presupuesto de educación.', 'El recorte sí es real, pero no hay ningún anuncio sobre eliminar el inglés.', array['Mezcla un hecho real con uno falso: es la técnica más efectiva.','No cita comunicado del MEP.','Busca indignación.']::text[], '{"who":"Profe Andrea","many":true,"band":"EDUCACIÓN","bg":"linear-gradient(135deg,#F2994A,#F2C94C)","emo":"📚","emo2":"🚫","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'No se encontró anuncio del MEP sobre eliminar inglés en primaria (búsqueda 09/10/2026). El recorte presupuestario de referencia es real (ver r_recorte).'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_hermano', 'Hermano de un ministro obtuvo una mejora salarial de ₡2 millones gracias a un puesto en el Gobierno', true, 'Función pública', 'CR Hoy (03/10/2026)', 'https://crhoy.com/nacionales/hermano-de-ministro-tuvo-mejora-salarial-de-₡2-millones-gracias-a-puesto-en-el-gobierno/', '2026-10-03'::date, 'Es real. CR Hoy lo publicó en octubre de 2026.', 'Lo publicó CR Hoy a inicios de octubre de 2026.', array[]::text[], '{"who":"Don Rigo","many":true,"band":"ESCÁNDALO","bg":"linear-gradient(135deg,#3E2723,#8D6E63)","emo":"💰","emo2":"🏛️","src_label":"Fuente citada: CR Hoy"}'::jsonb, 'verificada', 'CR Hoy, 03/10/2026: pasó de ₡2,1 millones (fiscal) a ₡4,2 millones (asesor en el ICE). Es un reportaje periodístico, no una resolución oficial.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ejercito', 'URGENTE: la Asamblea Legislativa aprobó en primer debate volver a crear el ejército', false, 'Política nacional', null, null, null, 'Es inventada para este juego.', 'Abolir el ejército está en la Constitución; cambiarlo sería un hecho histórico con cobertura mundial.', array['Mayúsculas y "URGENTE" para generar alarma.','Sería una reforma constitucional: imposible que pase en silencio.','No hay votación registrada ni medio que lo publique.']::text[], '{"who":"Tío Fernando","many":true,"band":"URGENTE","bg":"linear-gradient(135deg,#33691E,#827717)","emo":"🪖","emo2":"🇨🇷","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'Artículo 12 de la Constitución Política proscribe el ejército como institución permanente. No hay registro de tal votación.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_bus', 'El pasaje de una ruta de bus en Alajuela pasó de ₡260 a ₡1.000', true, 'Transporte y costo de vida', 'La Teja (07/10/2026)', 'https://www.lateja.cr/finanzas-y-tecnologia/bus-de-ruta-de-alajuela-amanecio-este-miercoles/PYIMWBYERVCPJMHNVS4ZA3DRWA/story/', '2026-10-07'::date, 'Es real. La Teja lo publicó el 2 de octubre de 2026.', 'Lo publicó La Teja el 2 de octubre de 2026.', array[]::text[], '{"who":"Vecina Lucía","many":true,"band":"INDIGNANTE","bg":"linear-gradient(135deg,#00695C,#4DB6AC)","emo":"🚌","emo2":"💸","src_label":"Fuente citada: La Teja"}'::jsonb, 'requiere_precision', 'Ruta 220 Alajuela–barrio San José. La solicitud se publicó en julio (CR Hoy) y ARESEP la aprobó a inicios de octubre; La Teja informó el cobro vigente el 07/10/2026. No se confirmó la fecha ''2 de octubre'' que mencionan la pista y la explicación.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ccss', 'La CCSS dejará de atender emergencias a personas que no tengan el seguro al día desde enero. ¡Pásalo!', false, 'Salud', null, null, null, 'Es inventada para este juego.', 'No hay comunicado de la CCSS y la atención de emergencias está garantizada por ley.', array['Pide "pásalo": las instituciones no comunican así.','Genera miedo sobre un tema de salud.','No hay comunicado oficial.']::text[], '{"who":"Mamá","many":false,"band":"SALUD","bg":"linear-gradient(135deg,#0277BD,#81D4FA)","emo":"🏥","emo2":"⛔","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'Sin comunicado de la CCSS. Conviene citar la norma que garantiza la atención de urgencias para fines académicos.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_recorte', 'Gremios rechazan recorte de ₡19 mil millones a educación: alertan que afectaría becas y comedores escolares', true, 'Educación', 'Diario Extra', 'https://www.diarioextra.com/videos/ecorte-presupuesto-educativo-costa-rica/', '2026-09-04'::date, 'Es real. Diario Extra lo publicó el 4 de septiembre de 2026.', 'Lo publicó Diario Extra el 4 de septiembre de 2026.', array[]::text[], '{"who":"Profe Andrea","many":false,"band":"PRESUPUESTO","bg":"linear-gradient(135deg,#4A148C,#9575CD)","emo":"✂️","emo2":"🍽️","src_label":"Fuente citada: Diario Extra"}'::jsonb, 'verificada', 'SIDE, SEC y APSE rechazan ~₡19 mil millones menos para el MEP en el presupuesto 2027; mencionan becas y comedores. La página muestra fechas contradictorias (metadatos 04/09/2026, texto 08/10/2026).'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_sinpe', 'A partir del 1 de noviembre SINPE Móvil cobrará ₡150 por cada transferencia. ¡Avísale a todos!', false, 'Finanzas personales', null, null, null, 'Es inventada para este juego.', 'El Banco Central no ha anunciado ningún cobro así.', array['Pide reenviarlo a todos.','Fecha cercana para que reacciones sin pensar.','Ningún enlace ni comunicado oficial.']::text[], '{"who":"Tía Marielos","many":true,"band":"⚠️ ATENCIÓN","bg":"linear-gradient(135deg,#C62828,#FF8A65)","emo":"📱","emo2":"💳","src_label":"Sin fuente"}'::jsonb, 'requiere_correccion', 'No existe un cobro fijo de ₡150 por transferencia. Sin embargo, desde octubre de 2025 varios bancos cobran comisión al superar montos diarios (CR Hoy, 16/10/2025: https://www.crhoy.com/varios-bancos-ya-estan-aplicando-cambios-en-sinpe-movil-enterese-aqui-cuales-son/). Participantes informados podrían considerarla plausible; la pista debería decir ''No hay un cobro fijo por cada transferencia; solo algunos bancos cobran por encima de ciertos montos diarios''.'
from public.studies where code = 'lo-reenviarias' and version = '1.0.0'
on conflict (study_id, item_key) do nothing;

insert into public.studies (code, version, title, description, status, config, changelog)
values ('lo-reenviarias', '2.0.0', '¿Lo reenviarías? — plataforma 2.0', 'Mismas 10 noticias, mismas preguntas, misma regla de puntuación. Cambios técnicos: puntuación calculada en servidor, orden aleatorio en servidor, temporizador siempre activo, guardado incremental con reintentos.', 'active', '{"items_per_session":10,"seconds_per_item":20,"hints_per_session":2,"show_crowd_feedback":false,"min_crowd_n":3,"timer_runs_with_reduced_motion":true,"max_sessions_per_minute":120,"public_stats_min_n":10,"percentile_min_n":20}'::jsonb, 'Técnico: puntuación/aciertos en servidor; respuestas correctas solo tras cada decisión; guardado por decisión; temporizador independiente de animaciones. Metodológico (registrado): se desactiva por defecto el porcentaje de la multitud durante el juego (influencia social); se añade aceptación informada explícita al iniciar.')
on conflict (code, version) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'opinion', 'pre', 'open', 'Si te llega una noticia impactante que no puedes verificar, ¿la compartes? ¿Por qué?', array[]::text[], 1, 3, 1500
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'verifica', 'pre', 'single', '¿Verificas una noticia antes de compartirla?', array['Siempre','A veces','Casi nunca']::text[], 2, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'compartio_falso', 'pre', 'single', '¿Has compartido algo que luego supiste que era falso?', array['Sí','No','No estoy seguro/a']::text[], 3, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'responsable', 'pre', 'single', 'Cuando una noticia falsa se vuelve viral, ¿quién tiene más responsabilidad?', array['Quien la crea','Quien la comparte','La red social','Todos por igual']::text[], 4, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.survey_questions (study_id, question_key, phase, kind, prompt, options, position, min_length, max_length)
select id, 'post_cambio', 'post', 'single', '¿Cambiarías tu forma de compartir noticias?', array['Sí, verificaría más','Tal vez','No, seguiré igual']::text[], 5, 0, 120
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, question_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_arancel', 'EE.UU. impone un arancel de 12,5% a Costa Rica por presunto trabajo forzoso en la cadena de suministro', true, 'Economía y comercio', 'La República (CR)', 'https://www.larepublica.net/noticia/ee-uu-cobrara-125-de-aranceles-a-exportaciones-ticas', '2026-07-23'::date, 'Es real. Ocurrió el 24 de julio de 2026.', 'La reportaron agencias internacionales y medios nacionales en julio de 2026.', array[]::text[], '{"who":"Tío Fernando","many":true,"band":"URGENTE","bg":"linear-gradient(135deg,#1F3B73,#B22234)","emo":"📦","emo2":"⛓️","src_label":"Fuente citada: AP / medios internacionales"}'::jsonb, 'requiere_precision', 'El arancel (de 10% a 12,5%, vigente 24/07/2026) se vincula a investigaciones de USTR sobre la falta de aplicación de una prohibición de importar bienes hechos con trabajo forzoso (60 economías), no a trabajo forzoso comprobado en la cadena costarricense; Infobae indica que aplica a ''parte de las exportaciones''. El titular simplifica. La fuente citada en la tarjeta (AP) no se localizó; se documenta La República, Infobae (25/07/2026) y Delfino. Fuentes adicionales: https://www.infobae.com/costa-rica/2026/07/25/eeuu-eleva-a-125-el-arancel-para-parte-de-las-exportaciones-de-costa-rica-por-cuestionamientos-sobre-trabajo-forzado/'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_marihuana', 'Desde noviembre será legal comprar marihuana recreativa en farmacias de Costa Rica', false, 'Política nacional', null, null, null, 'Es inventada para este juego.', 'Ningún medio la reporta y un cambio de ley así pasaría por la Asamblea con mucha cobertura.', array['No dice quién lo anunció ni cita ninguna ley.','Un cambio de ley así sería noticia en todos los medios.','Toca un tema polémico para que reacciones rápido.']::text[], '{"who":"Grupo U 🎓","many":false,"band":"NACIONAL","bg":"linear-gradient(135deg,#2F7D32,#A5D6A7)","emo":"🌿","emo2":"💊","src_label":"Sin fuente"}'::jsonb, 'requiere_correccion', 'La afirmación específica (venta legal en farmacias desde noviembre) es falsa. Pero existe un proyecto de ley del Gobierno sobre marihuana recreativa con cobertura mediática (p. ej. https://observador.cr/gobierno-enviara-proyecto-de-ley-para-legalizar-la-marihuana-recreativa-en-costa-rica/), por lo que la pista ''Ningún medio la reporta'' es imprecisa: sugerir ''Hay un proyecto en discusión, pero no es ley ni autoriza venta en farmacias''.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_cuba', 'Costa Rica rompe relaciones diplomáticas con Cuba y ordena cerrar su embajada', true, 'Política internacional', 'ADN40 / Reuters (18/03/2026)', 'https://www.adn40.mx/internacional/2026-03-18/costa-rica-cierra-su-embajada-en-cuba-la-habana-apunta-a-presiones-trump', '2026-03-18'::date, 'Es real. Sucedió el 18 de marzo de 2026.', 'Se publicó en medios nacionales e internacionales en marzo de 2026.', array[]::text[], '{"who":"Mamá","many":false,"band":"INTERNACIONAL","bg":"linear-gradient(135deg,#0B3D91,#CF142B)","emo":"🏛️","emo2":"✂️","src_label":"Fuente citada: CBS News"}'::jsonb, 'requiere_precision', 'El 17-18/03/2026 Costa Rica cerró su embajada y pidió la salida del personal diplomático cubano. Según Cuba (Tico Times, 20/09/2026), la nota de marzo no declaró una ruptura formal; el canciller confirmó la ruptura el 19/09/2026. ''Rompe relaciones'' en marzo es discutible. No se localizó la nota de CBS News citada. Ver https://ticotimes.net/2026/09/20/costa-rica-cuba-diplomatic-relations-break'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ingles', 'Por el recorte de presupuesto, el MEP eliminará las clases de inglés en primaria a partir de 2027', false, 'Educación', null, null, null, 'Es inventada para este juego, pero se monta sobre una noticia real: el recorte al presupuesto de educación.', 'El recorte sí es real, pero no hay ningún anuncio sobre eliminar el inglés.', array['Mezcla un hecho real con uno falso: es la técnica más efectiva.','No cita comunicado del MEP.','Busca indignación.']::text[], '{"who":"Profe Andrea","many":true,"band":"EDUCACIÓN","bg":"linear-gradient(135deg,#F2994A,#F2C94C)","emo":"📚","emo2":"🚫","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'No se encontró anuncio del MEP sobre eliminar inglés en primaria (búsqueda 09/10/2026). El recorte presupuestario de referencia es real (ver r_recorte).'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_hermano', 'Hermano de un ministro obtuvo una mejora salarial de ₡2 millones gracias a un puesto en el Gobierno', true, 'Función pública', 'CR Hoy (03/10/2026)', 'https://crhoy.com/nacionales/hermano-de-ministro-tuvo-mejora-salarial-de-₡2-millones-gracias-a-puesto-en-el-gobierno/', '2026-10-03'::date, 'Es real. CR Hoy lo publicó en octubre de 2026.', 'Lo publicó CR Hoy a inicios de octubre de 2026.', array[]::text[], '{"who":"Don Rigo","many":true,"band":"ESCÁNDALO","bg":"linear-gradient(135deg,#3E2723,#8D6E63)","emo":"💰","emo2":"🏛️","src_label":"Fuente citada: CR Hoy"}'::jsonb, 'verificada', 'CR Hoy, 03/10/2026: pasó de ₡2,1 millones (fiscal) a ₡4,2 millones (asesor en el ICE). Es un reportaje periodístico, no una resolución oficial.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ejercito', 'URGENTE: la Asamblea Legislativa aprobó en primer debate volver a crear el ejército', false, 'Política nacional', null, null, null, 'Es inventada para este juego.', 'Abolir el ejército está en la Constitución; cambiarlo sería un hecho histórico con cobertura mundial.', array['Mayúsculas y "URGENTE" para generar alarma.','Sería una reforma constitucional: imposible que pase en silencio.','No hay votación registrada ni medio que lo publique.']::text[], '{"who":"Tío Fernando","many":true,"band":"URGENTE","bg":"linear-gradient(135deg,#33691E,#827717)","emo":"🪖","emo2":"🇨🇷","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'Artículo 12 de la Constitución Política proscribe el ejército como institución permanente. No hay registro de tal votación.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_bus', 'El pasaje de una ruta de bus en Alajuela pasó de ₡260 a ₡1.000', true, 'Transporte y costo de vida', 'La Teja (07/10/2026)', 'https://www.lateja.cr/finanzas-y-tecnologia/bus-de-ruta-de-alajuela-amanecio-este-miercoles/PYIMWBYERVCPJMHNVS4ZA3DRWA/story/', '2026-10-07'::date, 'Es real. La Teja lo publicó el 2 de octubre de 2026.', 'Lo publicó La Teja el 2 de octubre de 2026.', array[]::text[], '{"who":"Vecina Lucía","many":true,"band":"INDIGNANTE","bg":"linear-gradient(135deg,#00695C,#4DB6AC)","emo":"🚌","emo2":"💸","src_label":"Fuente citada: La Teja"}'::jsonb, 'requiere_precision', 'Ruta 220 Alajuela–barrio San José. La solicitud se publicó en julio (CR Hoy) y ARESEP la aprobó a inicios de octubre; La Teja informó el cobro vigente el 07/10/2026. No se confirmó la fecha ''2 de octubre'' que mencionan la pista y la explicación.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_ccss', 'La CCSS dejará de atender emergencias a personas que no tengan el seguro al día desde enero. ¡Pásalo!', false, 'Salud', null, null, null, 'Es inventada para este juego.', 'No hay comunicado de la CCSS y la atención de emergencias está garantizada por ley.', array['Pide "pásalo": las instituciones no comunican así.','Genera miedo sobre un tema de salud.','No hay comunicado oficial.']::text[], '{"who":"Mamá","many":false,"band":"SALUD","bg":"linear-gradient(135deg,#0277BD,#81D4FA)","emo":"🏥","emo2":"⛔","src_label":"Sin fuente"}'::jsonb, 'ficticia_documentada', 'Sin comunicado de la CCSS. Conviene citar la norma que garantiza la atención de urgencias para fines académicos.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'r_recorte', 'Gremios rechazan recorte de ₡19 mil millones a educación: alertan que afectaría becas y comedores escolares', true, 'Educación', 'Diario Extra', 'https://www.diarioextra.com/videos/ecorte-presupuesto-educativo-costa-rica/', '2026-09-04'::date, 'Es real. Diario Extra lo publicó el 4 de septiembre de 2026.', 'Lo publicó Diario Extra el 4 de septiembre de 2026.', array[]::text[], '{"who":"Profe Andrea","many":false,"band":"PRESUPUESTO","bg":"linear-gradient(135deg,#4A148C,#9575CD)","emo":"✂️","emo2":"🍽️","src_label":"Fuente citada: Diario Extra"}'::jsonb, 'verificada', 'SIDE, SEC y APSE rechazan ~₡19 mil millones menos para el MEP en el presupuesto 2027; mencionan becas y comedores. La página muestra fechas contradictorias (metadatos 04/09/2026, texto 08/10/2026).'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
insert into public.news_items (study_id, item_key, headline, is_real, category, source_name, source_url, source_published_on, explanation, hint, red_flags, display, validation_status, validation_notes)
select id, 'f_sinpe', 'A partir del 1 de noviembre SINPE Móvil cobrará ₡150 por cada transferencia. ¡Avísale a todos!', false, 'Finanzas personales', null, null, null, 'Es inventada para este juego.', 'El Banco Central no ha anunciado ningún cobro así.', array['Pide reenviarlo a todos.','Fecha cercana para que reacciones sin pensar.','Ningún enlace ni comunicado oficial.']::text[], '{"who":"Tía Marielos","many":true,"band":"⚠️ ATENCIÓN","bg":"linear-gradient(135deg,#C62828,#FF8A65)","emo":"📱","emo2":"💳","src_label":"Sin fuente"}'::jsonb, 'requiere_correccion', 'No existe un cobro fijo de ₡150 por transferencia. Sin embargo, desde octubre de 2025 varios bancos cobran comisión al superar montos diarios (CR Hoy, 16/10/2025: https://www.crhoy.com/varios-bancos-ya-estan-aplicando-cambios-en-sinpe-movil-enterese-aqui-cuales-son/). Participantes informados podrían considerarla plausible; la pista debería decir ''No hay un cobro fijo por cada transferencia; solo algunos bancos cobran por encima de ciertos montos diarios''.'
from public.studies where code = 'lo-reenviarias' and version = '2.0.0'
on conflict (study_id, item_key) do nothing;
